funciones_sitio_homepage:
    path:     /
    defaults: { _controller: FuncionesSitioBundle:Default:index }

calificacion_pelicula:
    path:     /reg_calificacion
    defaults: { _controller: FuncionesSitioBundle:FuncionesSitio:calificarPelicula }
    
crear_lista:
    path:     /crearListaVistas
    defaults: { _controller: FuncionesSitioBundle:FuncionesSitio:crearListaVistas }
    
adicionar_pelicula_lista:
    path:     /adicionarPeliculaLista
    defaults: { _controller: FuncionesSitioBundle:FuncionesSitio:adicionarPeliculaLista}
    
marcar_vista:
    path:   /marcarVista
    defaults: { _controller: FuncionesSitioBundle:FuncionesSitio:adicionarPeliculaListaVistas}

marcar_por_ver:
    path:   /marcarPorVer
    defaults: { _controller: FuncionesSitioBundle:FuncionesSitio:adicionarPeliculaListaPorVer}

adicionar_lista:
    path: /adicionarLista
    defaults: { _controller: FuncionesSitioBundle:FuncionesSitio:crearListaPersonalizada}
    
adicionar_pelicula_lista_personalizada:
    path: /adicionarPeliculaListaPersonalizada
    defaults: { _controller: FuncionesSitioBundle:FuncionesSitio:adicionarPeliculaListaPersonalizada}

eliminar_pelicula_lista_personalizada:
    path: /eliminarPeliculaColeccionPersonalizada
    defaults: { _controller: FuncionesSitioBundle:FuncionesSitio:eliminarPeliculaColeccionPersonalizada}

eliminar_coleccion_personalizada:
    path: /eliminarColeccionPersonalizada
    defaults: { _controller: FuncionesSitioBundle:FuncionesSitio:eliminarColeccionPersonalizada}
    
cambiar_nombre_coleccion:
    path: /cambiarNombreColeccion
    defaults: { _controller: FuncionesSitioBundle:FuncionesSitio:cambiarNombreColeccion}