vista_homepage:
    path:     /
    defaults: { _controller: VistaBundle:Default:iniciarIndex }
    
pelicula:
    path:      /buscar/{consulta}/{numero_pagina}
    defaults: { _controller: VistaBundle:Default:verResultadosBusqueda }
    

pelicula_consulta_barra:
    path:      /buscar/{consulta}/
    defaults:  { _controller: VistaBundle:Default:verResultadosBusqueda, numero_pagina 1}
    
pelicula_consulta_sin_barra:
    path:      /buscar/{consulta}
    defaults:  { _controller: VistaBundle:Default:verResultadosBusqueda, numero_pagina 1}
    
    
    
show:
    path:      /secret/buscar/show/{consulta}/{numero_pagina}
    defaults: { _controller: VistaBundle:Default:verResultadosBusquedaShow }
    

show_consulta_barra:
    path:      /secret/buscar/show/{consulta}/
    defaults:  { _controller: VistaBundle:Default:verResultadosBusquedaShow, numero_pagina 1}
    
show_consulta_sin_barra:
    path:      /secret/buscar/show/{consulta}
    defaults:  { _controller: VistaBundle:Default:verResultadosBusquedaShow, numero_pagina 1}
    
#generos:
#    path:      /generos/{_locale}
#    defaults:  { _controller: APITheMovieDataBaseBundle:API:listaGeneros, _locale: en }
    
    
generos_barra:
    path:      /generos
    defaults:  { _controller: VistaBundle:Default:verListaGeneros }
    
    
pelicula_barra:
    path:      /buscar/
    defaults:  { _controller: VistaBundle:Default:index }

mostrarPelicula:
    path:      /mostrarPelicula/{id}
    defaults:  { _controller: VistaBundle:Default:verPelicula }

mostrarPelicula_minuscula:
    path:      /mostrarpelicula/{id}
    defaults:  { _controller: VistaBundle:Default:verPelicula }

