login:
    resource: "@LoginBundle/Resources/config/routing.yml"
    prefix:   /

vista:
    resource: "@VistaBundle/Resources/config/routing.yml"
    prefix:   /vista/

api_the_movie_data_base:
    resource: "@APITheMovieDataBaseBundle/Resources/config/routing.yml"
    prefix:   /movie_database/

tinker_soft_usuarios:
    resource: "@TinkerSoftUsuariosBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
