tinker_soft_reportes:
    resource: "@TinkerSoftReportesBundle/Resources/config/routing.yml"
    prefix:   /

funciones_sitio:
    resource: "@FuncionesSitioBundle/Resources/config/routing.yml"
    prefix:   /

login:
    resource: "@LoginBundle/Resources/config/routing.yml"
    prefix:   /login/

vista:
    resource: "@VistaBundle/Resources/config/routing.yml"
    prefix:   /vista/

api_the_movie_data_base:
    resource: "@APITheMovieDataBaseBundle/Resources/config/routing.yml"
    prefix:   /movie_database/

tinker_soft_usuarios:
    resource: "@TinkerSoftUsuariosBundle/Resources/config/routing.yml"
    prefix:   /
    
tinker_soft_funciones:
    resource: "@FuncionesSitioBundle/Resources/config/routing.yml"
    prefix:   /funciones
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
