

login_action:
    path:     /procesador
    defaults: { _controller: LoginBundle:Login:login }

logout_action:
    path:     /logout
    defaults: { _controller: LoginBundle:Login:loginOut }
    
registro_generos_action:
    path:     /procesadorg
    defaults: { _controller: LoginBundle:Login:registrarGustos }